#+title: Meetup@Sfeir - <2013-02-26 Tue 19:00-22:00>
#+author: cpug members

Un ultra rapide sommaire de l'évènement.

* Tour de table

Tour de table ou chacun s'est présenté
Globalement, développeurs du monde jvm, des enseignant/chercheur et développeur c++.

* Présentation

** Petite application clojure/compojure/hiccup

Pas de lien possible de l'application présentée - [[https://github.com/ardumont/geekteek][Application à architecture identique]]

** Introduction a [[https://github.com/drcode/webfui][webfui]]

Pour ceux qui n'ont pas pu être là, ça ressemblait à [[https://www.youtube.com/watch?v%3DHeI5-D7SQe8][cette présentation par l'auteur]].

Aussi vivement recommandé :
- Le [[https://docs.google.com/document/d/1KQn_saQurqgvxHiyuOZ7twK4K_w_VftBHrPKJolwEZ8/edit][document de design]] de WebFUI.
- Il explique pas à pas les enjeux qui ont mené aux décisions prises
  dans le framework.
- Et dont sont dérivés tout les exemples de code ainsi que la présentation ci-dessus.

** Pas de code produit (pas encore :D)

* Vidéos
Au cours de la soirée, des liens ont été échangés, principalement sur des vidéos:

- [[http://skillsmatter.com/podcast/scala/a-practical-tour-of-clojure-web-development][Sur l'immutabilité et les documents web]]
- [[http://vimeo.com/52831373][Encore sur l'immutabilité dans les systèmes]]
- [[http://blip.tv/clojure/neal-ford-neal-s-master-plan-for-clojure-enterprise-mindshare-domination-5953926][Neal Ford's master plan for clojure enterprise mindshare domination]]
- [[http://skillsmatter.com/podcast/scala/clojure-at-nokia-entertainment][Exemple d'utilisation progressive de Clojure en entreprise (Nokia)]]
- [[http://www.infoq.com/presentations/What-Sucks-about-Clojure-and-Why-You-ll-Love-It-Anyway][What sucks about clojure and why you'll love it anyway]]

* Emacs
Il semble que Clojure ait fait naître quelques vocations pour Emacs,
voire pour [[http://orgmode.org/][org mode]]. Un exemple de (tout ‽) [[http://doc.norang.ca/org-mode.html][ce qu'il est possible de
faire]] !
